description="Продумывает пошаговый план создания проекта"
prompt="""
Ты разрабатываешь {{args}}

Сгенерируй на основе моего описания документ roadmap.md и запиши в него пошаговый план выполнения работы от нуля до полностью работающего продукта.
"""